version: '3.7'
services:
    mysql:
        container_name: ai_bot_mysql
        image: 'mysql:8.0'
        restart: 'always'
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - './docker/mysql/conf.d:/etc/mysql/conf.d'
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    phpmyadmin:
        container_name: ai_bot_pma
        image: 'phpmyadmin/phpmyadmin'
        restart: 'always'
        ports: ['${IFACE}:${PHP_ADMIN_PORT}:80']
        environment:
            PMA_HOST: 'mysql'
            PMA_ABSOLUTE_URI: 'https://ilkarvet.ru/tg-ai-bot-phpmyadmin/'
            PMA_USER: ${DATABASE_USERNAME}
            PMA_PASSWORD: ${DATABASE_PASSWORD}
    migrations:
        container_name: ai_bot_migrations
        build:
            context: .
            dockerfile: './docker/migrations/Dockerfile'
        depends_on:
        - mysql
        environment:
            DATABASE_HOST_MIGRATIONS: 'mysql'
            DATABASE_PORT_MIGRATIONS: '3306'
            # PROD: ${PROD}
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    bot:
        container_name: ai_bot
        build:
            context: .
            dockerfile: './docker/bot/Dockerfile'
        restart: 'always'
        depends_on:
          - mysql
        environment:
            DATABASE_HOST_MIGRATIONS: ${DATABASE_HOST_MIGRATIONS}
            DATABASE_PORT_MIGRATIONS: ${DATABASE_PORT_MIGRATIONS}
            PROD: ${PROD}
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            BOT_TOKEN: ${BOT_TOKEN}
    server:
        container_name: ai_server
        build:
            context: .
            dockerfile: './docker/backend/Dockerfile'
        restart: 'always'
        ports: ['${IFACE}:5000:5000']
        depends_on:
          - mysql
        environment:
            DATABASE_HOST_MIGRATIONS: ${DATABASE_HOST_MIGRATIONS}
            DATABASE_PORT_MIGRATIONS: ${DATABASE_PORT_MIGRATIONS}
            PROD: ${PROD}
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            BOT_TOKEN: ${BOT_TOKEN}
            YANDEX_DISK_TOKEN: ${YANDEX_DISK_TOKEN}
    frontend:
        container_name: ai_frontend
        build:
            context: .
            dockerfile: './docker/frontend/Dockerfile'
        restart: 'always'
        ports: ['${IFACE}:89:5000']
        depends_on:
          - mysql
        environment:
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            FRONTEND_SECRET_KEY: ${FRONTEND_SECRET_KEY}
volumes:
  db_data: