"""Table video_clips columns

Revision ID: 14a207bf6ab1
Revises: c9fa8946bf17
Create Date: 2023-08-25 17:07:57.079142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a207bf6ab1'
down_revision = 'c9fa8946bf17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_clips', sa.Column('url', sa.String(length=800), nullable=True))
    op.add_column('video_clips', sa.Column('path', sa.String(length=500), nullable=True))
    op.add_column('video_clips', sa.Column('md5', sa.String(length=500), nullable=True))
    op.add_column('video_clips', sa.Column('category', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_video_clips_category'), 'video_clips', ['category'], unique=False)
    op.create_index(op.f('ix_video_clips_md5'), 'video_clips', ['md5'], unique=False)
    op.create_index(op.f('ix_video_clips_path'), 'video_clips', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_clips_path'), table_name='video_clips')
    op.drop_index(op.f('ix_video_clips_md5'), table_name='video_clips')
    op.drop_index(op.f('ix_video_clips_category'), table_name='video_clips')
    op.drop_column('video_clips', 'category')
    op.drop_column('video_clips', 'md5')
    op.drop_column('video_clips', 'path')
    op.drop_column('video_clips', 'url')
    # ### end Alembic commands ###
