"""Logs,record_date

Revision ID: 289087107539
Revises: 81412f8f2701
Create Date: 2023-11-26 10:28:52.015019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289087107539'
down_revision = '81412f8f2701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('record_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'record_date')
    # ### end Alembic commands ###
