"""Users column final_clip_size

Revision ID: 2bb7502cae4b
Revises: 33aa04075517
Create Date: 2023-09-21 15:27:11.331690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb7502cae4b'
down_revision = '33aa04075517'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('final_clip_size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_final_clip_size'), 'users', ['final_clip_size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_final_clip_size'), table_name='users')
    op.drop_column('users', 'final_clip_size')
    # ### end Alembic commands ###
