"""render_hosts

Revision ID: 2d1f40a09897
Revises: 680cb6eed7d2
Create Date: 2023-08-14 22:31:32.941435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1f40a09897'
down_revision = '680cb6eed7d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('render_hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('render_host', sa.String(length=50), nullable=True),
    sa.Column('network_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_hosts_network_status'), 'render_hosts', ['network_status'], unique=False)
    op.create_index(op.f('ix_render_hosts_render_host'), 'render_hosts', ['render_host'], unique=False)
    op.add_column('users', sa.Column('notice', sa.Text(length=50), nullable=True))
    op.create_index(op.f('ix_users_clip_name'), 'users', ['clip_name'], unique=False)
    op.create_index(op.f('ix_users_render_host'), 'users', ['render_host'], unique=False)
    op.create_index(op.f('ix_users_render_time'), 'users', ['render_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_render_time'), table_name='users')
    op.drop_index(op.f('ix_users_render_host'), table_name='users')
    op.drop_index(op.f('ix_users_clip_name'), table_name='users')
    op.drop_column('users', 'notice')
    op.drop_index(op.f('ix_render_hosts_render_host'), table_name='render_hosts')
    op.drop_index(op.f('ix_render_hosts_network_status'), table_name='render_hosts')
    op.drop_table('render_hosts')
    # ### end Alembic commands ###
