"""Logs table

Revision ID: 33aa04075517
Revises: 5e035fdc480b
Create Date: 2023-09-16 10:05:43.827993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33aa04075517'
down_revision = '5e035fdc480b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_log'), 'logs', ['log'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_log'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
