"""Table users column photo

Revision ID: 3951cafcd19e
Revises: 6c23f3d443cb
Create Date: 2023-09-13 00:40:57.729809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3951cafcd19e'
down_revision = '6c23f3d443cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.LargeBinary(length=4294967295), nullable=False))
    op.execute("ALTER TABLE users MODIFY photo longblob NULL AFTER email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###
