"""Table tg_bot,tg_users

Revision ID: 4539fb770d23
Revises: 2bb7502cae4b
Create Date: 2023-09-30 18:43:38.982468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4539fb770d23'
down_revision = '2bb7502cae4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('language_code', sa.String(length=50), nullable=True),
    sa.Column('tg_user_id', sa.String(length=50), nullable=False),
    sa.Column('reg_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_users_email'), 'tg_users', ['email'], unique=False)
    op.create_index(op.f('ix_tg_users_language_code'), 'tg_users', ['language_code'], unique=False)
    op.create_index(op.f('ix_tg_users_name'), 'tg_users', ['name'], unique=False)
    op.create_index(op.f('ix_tg_users_surname'), 'tg_users', ['surname'], unique=False)
    op.create_index(op.f('ix_tg_users_tg_user_id'), 'tg_users', ['tg_user_id'], unique=True)
    op.create_index(op.f('ix_tg_users_username'), 'tg_users', ['username'], unique=False)
    op.create_table('tg_bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.String(length=50), nullable=False),
    sa.Column('bot_step', sa.String(length=50), nullable=True),
    sa.Column('step_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tg_user_id'], ['tg_users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_bot_bot_step'), 'tg_bot', ['bot_step'], unique=False)
    op.create_index(op.f('ix_tg_bot_tg_user_id'), 'tg_bot', ['tg_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_bot_tg_user_id'), table_name='tg_bot')
    op.drop_index(op.f('ix_tg_bot_bot_step'), table_name='tg_bot')
    op.drop_table('tg_bot')
    op.drop_index(op.f('ix_tg_users_username'), table_name='tg_users')
    op.drop_index(op.f('ix_tg_users_tg_user_id'), table_name='tg_users')
    op.drop_index(op.f('ix_tg_users_surname'), table_name='tg_users')
    op.drop_index(op.f('ix_tg_users_name'), table_name='tg_users')
    op.drop_index(op.f('ix_tg_users_language_code'), table_name='tg_users')
    op.drop_index(op.f('ix_tg_users_email'), table_name='tg_users')
    op.drop_table('tg_users')
    # ### end Alembic commands ###
