"""Users,photo longblob

Revision ID: 5e035fdc480b
Revises: 3951cafcd19e
Create Date: 2023-09-13 10:03:39.218966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e035fdc480b'
down_revision = '3951cafcd19e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo',
               existing_type=mysql.LONGBLOB(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo',
               existing_type=mysql.LONGBLOB(),
               nullable=True)
    # ### end Alembic commands ###
