"""render_hosts column render_enabled

Revision ID: 631f6a2b5ddc
Revises: 14a207bf6ab1
Create Date: 2023-08-28 19:38:28.286756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631f6a2b5ddc'
down_revision = '14a207bf6ab1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('render_hosts', sa.Column('render_enabled', sa.Boolean(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('render_hosts', 'render_enabled')
    # ### end Alembic commands ###
