"""Photo table add column record_date

Revision ID: 680cb6eed7d2
Revises: 3d8c5b72637b
Create Date: 2022-07-30 01:57:30.266209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680cb6eed7d2'
down_revision = 'c0a0e474ba48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('record_date', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_photos_record_date'), 'photos', ['record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_record_date'), table_name='photos')
    op.drop_column('photos', 'record_date')
    # ### end Alembic commands ###
