"""Video_clips url uniq migration

Revision ID: 6c23f3d443cb
Revises: 9e277c570bea
Create Date: 2023-09-07 00:47:50.351178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c23f3d443cb'
down_revision = '9e277c570bea'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE video_clips')
    op.alter_column('video_clips', 'url', type_=sa.String(length=500))
    op.create_index(op.f('ix_video_clips_url'), 'video_clips', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_clips_url'), table_name='video_clips')
    # ### end Alembic commands ###
