"""video_clip table column fix

Revision ID: 770baccc6d06
Revises: b249d75760e9
Create Date: 2023-08-17 12:16:10.954223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '770baccc6d06'
down_revision = 'b249d75760e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_clips', sa.Column('name_ru', sa.String(length=50), nullable=True))
    op.add_column('video_clips', sa.Column('name_en', sa.String(length=50), nullable=True))
    op.drop_index('ix_video_clips_name', table_name='video_clips')
    op.create_index(op.f('ix_video_clips_name_en'), 'video_clips', ['name_en'], unique=True)
    op.create_index(op.f('ix_video_clips_name_ru'), 'video_clips', ['name_ru'], unique=False)
    op.drop_column('video_clips', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_clips', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_video_clips_name_ru'), table_name='video_clips')
    op.drop_index(op.f('ix_video_clips_name_en'), table_name='video_clips')
    op.create_index('ix_video_clips_name', 'video_clips', ['name'], unique=False)
    op.drop_column('video_clips', 'name_en')
    op.drop_column('video_clips', 'name_ru')
    # ### end Alembic commands ###
