"""Tables users fix photo null

Revision ID: 81412f8f2701
Revises: 4539fb770d23
Create Date: 2023-09-30 20:14:41.940558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81412f8f2701'
down_revision = '4539fb770d23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Name', new_column_name='name', existing_type=sa.String(50))
    op.alter_column('users', 'Surname', new_column_name='surname', existing_type=sa.String(50))
    op.alter_column('users', 'photo',
               existing_type=mysql.LONGBLOB(),
               nullable=True)
    op.alter_column('users', 'clip_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'record_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index('ix_users_Name', table_name='users')
    op.drop_index('ix_users_Surname', table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name', new_column_name='Name', existing_type=sa.String(50))
    op.alter_column('users', 'surname', new_column_name='Surname', existing_type=sa.String(50))
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index('ix_users_Surname', 'users', ['Surname'], unique=False)
    op.create_index('ix_users_Name', 'users', ['Name'], unique=False)
    op.alter_column('users', 'record_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'clip_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'photo',
               existing_type=mysql.LONGBLOB(),
               nullable=False)
    # ### end Alembic commands ###
