"""Table paid rename to payments

Revision ID: 9e277c570bea
Revises: b3c2567f4bcb
Create Date: 2023-09-06 11:24:35.753073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e277c570bea'
down_revision = 'b3c2567f4bcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.String(length=50), nullable=False),
    sa.Column('payments_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payments_date'), 'payments', ['payments_date'], unique=False)
    op.create_index(op.f('ix_payments_tg_user_id'), 'payments', ['tg_user_id'], unique=False)
    op.drop_index('ix_paid_paid_date', table_name='paid')
    op.drop_index('ix_paid_tg_user_id', table_name='paid')
    op.drop_table('paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paid',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('paid_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_paid_tg_user_id', 'paid', ['tg_user_id'], unique=False)
    op.create_index('ix_paid_paid_date', 'paid', ['paid_date'], unique=False)
    op.drop_index(op.f('ix_payments_tg_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payments_date'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
