"""Table video_clips columns

Revision ID: ae4c30d79585
Revises: c9fa8946bf17
Create Date: 2023-08-25 14:38:56.128031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4c30d79585'
down_revision = 'c9fa8946bf17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
