"""Videoclips name_en uniq_index

Revision ID: b3c2567f4bcb
Revises: 631f6a2b5ddc
Create Date: 2023-09-01 13:54:06.881085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3c2567f4bcb'
down_revision = '631f6a2b5ddc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_paid', table_name='users')
    op.drop_column('users', 'paid')
    op.drop_index('ix_video_clips_name_en', table_name='video_clips')
    op.create_index(op.f('ix_video_clips_name_en'), 'video_clips', ['name_en'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_clips_name_en'), table_name='video_clips')
    op.create_index('ix_video_clips_name_en', 'video_clips', ['name_en'], unique=False)
    op.add_column('users', sa.Column('paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_users_paid', 'users', ['paid'], unique=False)
    # ### end Alembic commands ###
