"""Users table add uts,paid bool columns

Revision ID: c0a0e474ba48
Revises: 4392d090c389
Create Date: 2022-07-30 01:00:14.366529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a0e474ba48'
down_revision = '9a337982abae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paid', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_paid'), 'users', ['paid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_paid'), table_name='users')
    op.drop_column('users', 'paid')
    # ### end Alembic commands ###
