"""Create paid table

Revision ID: c9fa8946bf17
Revises: cefbb91e6c0c
Create Date: 2023-08-25 10:25:06.204652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fa8946bf17'
down_revision = 'cefbb91e6c0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.String(length=50), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paid_paid_date'), 'paid', ['paid_date'], unique=False)
    op.create_index(op.f('ix_paid_tg_user_id'), 'paid', ['tg_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paid_tg_user_id'), table_name='paid')
    op.drop_index(op.f('ix_paid_paid_date'), table_name='paid')
    op.drop_table('paid')
    # ### end Alembic commands ###
