"""Users table add columns

Revision ID: cefbb91e6c0c
Revises: a4b5879c1238
Create Date: 2023-08-25 10:16:33.894840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cefbb91e6c0c'
down_revision = 'a4b5879c1238'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('Surname', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('render_counter', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_Name'), 'users', ['Name'], unique=False)
    op.create_index(op.f('ix_users_Surname'), 'users', ['Surname'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_render_counter'), 'users', ['render_counter'], unique=False)
    # op.drop_index('ix_users_paid', table_name='users')
    # op.drop_column('users', 'paid')
    op.execute("ALTER TABLE users MODIFY Name varchar(50) NULL AFTER id")
    op.execute("ALTER TABLE users MODIFY Surname varchar(50) NULL AFTER Name")
    op.execute("ALTER TABLE users MODIFY email varchar(50) NULL AFTER Surname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_render_counter'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_Surname'), table_name='users')
    op.drop_index(op.f('ix_users_Name'), table_name='users')
    op.create_index('ix_users_paid', 'users', ['paid'], unique=False)
    op.drop_column('users', 'render_counter')
    op.drop_column('users', 'email')
    op.drop_column('users', 'Surname')
    op.drop_column('users', 'Name')
    # ### end Alembic commands ###
