"""table notification

Revision ID: e7a116ddbe83
Revises: 289087107539
Create Date: 2023-12-25 22:26:24.903100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a116ddbe83'
down_revision = '289087107539'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=500), nullable=True),
    sa.Column('language_code', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.Column('count_summ', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_notification_count_summ'), 'bot_notification', ['count_summ'], unique=False)
    op.create_index(op.f('ix_bot_notification_language_code'), 'bot_notification', ['language_code'], unique=False)
    op.create_index(op.f('ix_bot_notification_message_text'), 'bot_notification', ['message_text'], unique=False)
    op.create_index(op.f('ix_bot_notification_status'), 'bot_notification', ['status'], unique=False)
    op.create_index(op.f('ix_bot_notification_type'), 'bot_notification', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_notification_type'), table_name='bot_notification')
    op.drop_index(op.f('ix_bot_notification_status'), table_name='bot_notification')
    op.drop_index(op.f('ix_bot_notification_message_text'), table_name='bot_notification')
    op.drop_index(op.f('ix_bot_notification_language_code'), table_name='bot_notification')
    op.drop_index(op.f('ix_bot_notification_count_summ'), table_name='bot_notification')
    op.drop_table('bot_notification')
    # ### end Alembic commands ###
