name: build-tags
on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main
jobs:
  steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ inputs.ref }}
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
      - name: Configure SSH
        run: |
          echo $SSH_HOST
          mkdir -p ~/.ssh/
          echo "${SSH_DEPLOY_KEY}" > ~/.ssh/ssh.key
          chmod 600 ~/.ssh/ssh.key
          cat >> ~/.ssh/config <<END
          Host remote
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/ssh.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy
        run: |
          DESTINATION_PATH="/home/tg_ai_bot/tg_ai_bot/"
          DOCKER_COMPOSE_FILE="docker-compose-production.yaml"
          rsync -avz --delete  --exclude='.env' --exclude='.git' --exclude='.github' --exclude='.gitignore' --exclude='media' --exclude='utils' ./ remote:$DESTINATION_PATH
          ssh remote "cd $DESTINATION_PATH && docker-compose -f $DOCKER_COMPOSE_FILE up -d --build"
          echo "Github Actions CI/CD pipeline completed"
      # - name: Run remote SSH
      #   run: |
      #     echo "Branch is ${{ github.ref }}; Workflow is ${{ github.workflow }}"
      #     ssh remote 'bash update.bash'
      #     if [ $? -ne 0 ]; then
      #       echo "Error while running pipeline "
      #       exit 255
      #     fi
      #     echo "Github Actions CI/CD pipeline completed"